# Pandas
* Introduction
* Pandas Data Structure
* Series Crud Operation
* series using list , dictionary&Ndarray
* Series Indexing
* Series Method

In [ ]:
import pandas as pd
pd.__version__        # version check karne ke liye

'3.0.5'

## Series
### A series is similar to a single columns of data

In [10]:
#Create a series object
s = pd.Series([10,20,30,40],name='counts')
s

0    10
1    20
2    30
3    40
Name: counts, dtype: int64

In [11]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
# String as index
s = pd.Series([145,142,38,13],index=['Abdul','Malik','Khan','Majid'],name='counts')
s

Abdul    145
Malik    142
Khan      38
Majid     13
Name: counts, dtype: int64

In [14]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [15]:
nan_ex = pd.Series([2,6,3,None])
print(nan_ex.count())

3

### Load Data from csv file into series

In [16]:
s1 = pd.read_csv(r"C:\Users\Abdul\OneDrive\Documents\stores.csv")

In [17]:
print(s1)

   StoreCode         StoreName     StoreType Location  OperatingCost  \
0     STR101  Electronics Zone  Electronincs    Delhi           21.0
1     STR102      Apparel Zone       Apparel    Delhi           21.0
2     STR103       Super Bazar  Super Market    Delhi           22.8
3     STR104      Super Market  Super Market    Delhi           21.4
4     STR105     Central Store  Super Market    Delhi           18.7
5     STR106      Apparel Zone       Apparel    Delhi           18.1
6     STR107     Fashion Bazar       Apparel    Delhi           14.3
7     STR108     Digital Bazar  Electronincs    Delhi           24.4
8     STR109  Electronics Zone  Electronincs  Chennai           22.8
9     STR110      Apparel Zone       Apparel  Chennai           19.2
10    STR111       Super Bazar  Super Market  Chennai           17.8
11    STR112      Super Market  Super Market  Chennai           16.4
12    STR113     Central Store  Super Market  Chennai           17.3
13    STR114      Apparel Zone       Apparel  Chennai           15.2
14    STR115     Fashion Bazar       Apparel  Chennai           10.4
15    STR116     Digital Bazar  Electronincs  Chennai           10.4
16    STR117  Electronics Zone  Electronincs   Mumbai           14.7
17    STR118      Apparel Zone       Apparel   Mumbai           32.4
18    STR119       Super Bazar  Super Market   Mumbai           30.4
19    STR120      Super Market  Super Market   Mumbai           33.9
20    STR121     Central Store  Super Market   Mumbai           21.5
21    STR122      Apparel Zone       Apparel   Mumbai           15.5
22    STR123     Fashion Bazar       Apparel   Mumbai           15.2
23    STR124     Digital Bazar  Electronincs   Mumbai           13.3
24    STR125  Electronics Zone  Electronincs  Kolkata           19.2
25    STR126      Apparel Zone       Apparel  Kolkata           27.3
26    STR127       Super Bazar  Super Market  Kolkata           26.0
27    STR128      Super Market  Super Market  Kolkata           30.4
28    STR129     Central Store  Super Market  Kolkata           15.8
29    STR130      Apparel Zone       Apparel  Kolkata           19.7
30    STR131     Fashion Bazar       Apparel  Kolkata           15.0
31    STR132     Digital Bazar  Electronincs  Kolkata           21.4

    Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0          60       160.0              110            3.90       2.620
1          60       160.0              110            3.90       2.875
2          40       108.0               93            3.85       2.320
3          60       258.0              110            3.08       3.215
4          80       360.0              175            3.15       3.440
5          60       225.0              105            2.76       3.460
6          80       360.0              245            3.21       3.570
7          40       146.7               62            3.69       3.190
8          40       140.8               95            3.92       3.150
9          60       167.6              123            3.92       3.440
10         60       167.6              123            3.92       3.440
11         80       275.8              180             NaN       4.070
12         80       275.8              180             NaN       3.730
13         80       275.8              180             NaN       3.780
14         80       472.0              205            2.93       5.250
15         80       460.0              215            3.00       5.424
16         80       440.0              230            3.23       5.345
17         40        78.7               66            4.08       2.200
18         40        75.7               52            4.93       1.615
19         40        71.1               65            4.22       1.835
20         40       120.1               97            3.70       2.465
21         80       318.0              150            2.76       3.520
22         80       304.0              150            3.15       3.435
23         80       350.0              245            3.73       3.840
24         80       400.0              175            3.08       3.845
25         40        79.0               66            4.08       1.935
26         40       120.3               91            4.43       2.140
27         40        95.1              113            3.77       1.513
28         80       351.0              264            4.22       3.170
29         60       145.0              175            3.62       2.770
30         80       301.0              335            3.54       3.570
31         40       121.0              109            4.11       2.780

    ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment
0           16.46         0               1       4             4
1           17.02         0               1       4             4
2           18.61         1               1       4             1
3           19.44         1               0       3             1
4           17.02         0               0       3             2
5           20.22         1               0       3             1
6           15.84         0               0       3             4
7           20.00         1               0       4             2
8           22.90         1               0       4             2
9           18.30         1               0       4             4
10          18.90         1               0       4             4
11          17.40         0               0       3             3
12          17.60         0               0       3             3
13          18.00         0               0       3             3
14          17.98         0               0       3             4
15          17.82         0               0       3             4
16          17.42         0               0       3             4
17          19.47         1               1       4             1
18          18.52         1               1       4             2
19          19.90         1               1       4             1
20          20.01         1               0       3             1
21          16.87         0               0       3             2
22          17.30         0               0       3             2
23          15.41         0               0       3             4
24          17.05         0               0       3             2
25          18.90         1               1       4             1
26          16.70         0               1       5             2
27          16.90         1               1       5             2
28          14.50         0               1       5             4
29          15.50         0               1       5             4
30          14.60         0               1       5             4
31          18.60         1               1       4             2

In [19]:
print(type(s1))

<class 'pandas.DataFrame'>

In [20]:
print(s1.head)

<bound method NDFrame.head of    StoreCode         StoreName     StoreType Location  OperatingCost  \
0     STR101  Electronics Zone  Electronincs    Delhi           21.0
1     STR102      Apparel Zone       Apparel    Delhi           21.0
2     STR103       Super Bazar  Super Market    Delhi           22.8
3     STR104      Super Market  Super Market    Delhi           21.4
4     STR105     Central Store  Super Market    Delhi           18.7
5     STR106      Apparel Zone       Apparel    Delhi           18.1
6     STR107     Fashion Bazar       Apparel    Delhi           14.3
7     STR108     Digital Bazar  Electronincs    Delhi           24.4
8     STR109  Electronics Zone  Electronincs  Chennai           22.8
9     STR110      Apparel Zone       Apparel  Chennai           19.2
10    STR111       Super Bazar  Super Market  Chennai           17.8
11    STR112      Super Market  Super Market  Chennai           16.4
12    STR113     Central Store  Super Market  Chennai           17.3
13    STR114      Apparel Zone       Apparel  Chennai           15.2
14    STR115     Fashion Bazar       Apparel  Chennai           10.4
15    STR116     Digital Bazar  Electronincs  Chennai           10.4
16    STR117  Electronics Zone  Electronincs   Mumbai           14.7
17    STR118      Apparel Zone       Apparel   Mumbai           32.4
18    STR119       Super Bazar  Super Market   Mumbai           30.4
19    STR120      Super Market  Super Market   Mumbai           33.9
20    STR121     Central Store  Super Market   Mumbai           21.5
21    STR122      Apparel Zone       Apparel   Mumbai           15.5
22    STR123     Fashion Bazar       Apparel   Mumbai           15.2
23    STR124     Digital Bazar  Electronincs   Mumbai           13.3
24    STR125  Electronics Zone  Electronincs  Kolkata           19.2
25    STR126      Apparel Zone       Apparel  Kolkata           27.3
26    STR127       Super Bazar  Super Market  Kolkata           26.0
27    STR128      Super Market  Super Market  Kolkata           30.4
28    STR129     Central Store  Super Market  Kolkata           15.8
29    STR130      Apparel Zone       Apparel  Kolkata           19.7
30    STR131     Fashion Bazar       Apparel  Kolkata           15.0
31    STR132     Digital Bazar  Electronincs  Kolkata           21.4

    Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0          60       160.0              110            3.90       2.620
1          60       160.0              110            3.90       2.875
2          40       108.0               93            3.85       2.320
3          60       258.0              110            3.08       3.215
4          80       360.0              175            3.15       3.440
5          60       225.0              105            2.76       3.460
6          80       360.0              245            3.21       3.570
7          40       146.7               62            3.69       3.190
8          40       140.8               95            3.92       3.150
9          60       167.6              123            3.92       3.440
10         60       167.6              123            3.92       3.440
11         80       275.8              180             NaN       4.070
12         80       275.8              180             NaN       3.730
13         80       275.8              180             NaN       3.780
14         80       472.0              205            2.93       5.250
15         80       460.0              215            3.00       5.424
16         80       440.0              230            3.23       5.345
17         40        78.7               66            4.08       2.200
18         40        75.7               52            4.93       1.615
19         40        71.1               65            4.22       1.835
20         40       120.1               97            3.70       2.465
21         80       318.0              150            2.76       3.520
22         80       304.0              150            3.15       3.435
23         80       350.0              245            3.73       3.840
24         80       400.0              175            3.08       3.845
25         40        79.0               66            4.08       1.935
26         40       120.3               91            4.43       2.140
27         40        95.1              113            3.77       1.513
28         80       351.0              264            4.22       3.170
29         60       145.0              175            3.62       2.770
30         80       301.0              335            3.54       3.570
31         40       121.0              109            4.11       2.780

    ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment
0           16.46         0               1       4             4
1           17.02         0               1       4             4
2           18.61         1               1       4             1
3           19.44         1               0       3             1
4           17.02         0               0       3             2
5           20.22         1               0       3             1
6           15.84         0               0       3             4
7           20.00         1               0       4             2
8           22.90         1               0       4             2
9           18.30         1               0       4             4
10          18.90         1               0       4             4
11          17.40         0               0       3             3
12          17.60         0               0       3             3
13          18.00         0               0       3             3
14          17.98         0               0       3             4
15          17.82         0               0       3             4
16          17.42         0               0       3             4
17          19.47         1               1       4             1
18          18.52         1               1       4             2
19          19.90         1               1       4             1
20          20.01         1               0       3             1
21          16.87         0               0       3             2
22          17.30         0               0       3             2
23          15.41         0               0       3             4
24          17.05         0               0       3             2
25          18.90         1               1       4             1
26          16.70         0               1       5             2
27          16.90         1               1       5             2
28          14.50         0               1       5             4
29          15.50         0               1       5             4
30          14.60         0               1       5             4
31          18.60         1               1       4             2  >

In [21]:
print(s1.head(4))

  StoreCode         StoreName     StoreType Location  OperatingCost  \
0    STR101  Electronics Zone  Electronincs    Delhi           21.0
1    STR102      Apparel Zone       Apparel    Delhi           21.0
2    STR103       Super Bazar  Super Market    Delhi           22.8
3    STR104      Super Market  Super Market    Delhi           21.4

   Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0         60       160.0              110            3.90       2.620
1         60       160.0              110            3.90       2.875
2         40       108.0               93            3.85       2.320
3         60       258.0              110            3.08       3.215

   ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment
0          16.46         0               1       4             4
1          17.02         0               1       4             4
2          18.61         1               1       4             1
3          19.44         1               0       3             1

In [22]:
s1.tail(12)

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
20,STR121,Central Store,Super Market,Mumbai,21.5,40,120.1,97,3.70,2.465,20.01,1,0,3,1
21,STR122,Apparel Zone,Apparel,Mumbai,15.5,80,318.0,150,2.76,3.520,16.87,0,0,3,2
22,STR123,Fashion Bazar,Apparel,Mumbai,15.2,80,304.0,150,3.15,3.435,17.30,0,0,3,2
23,STR124,Digital Bazar,Electronincs,Mumbai,13.3,80,350.0,245,3.73,3.840,15.41,0,0,3,4
24,STR125,Electronics Zone,Electronincs,Kolkata,19.2,80,400.0,175,3.08,3.845,17.05,0,0,3,2
25,STR126,Apparel Zone,Apparel,Kolkata,27.3,40,79.0,66,4.08,1.935,18.90,1,1,4,1
26,STR127,Super Bazar,Super Market,Kolkata,26.0,40,120.3,91,4.43,2.140,16.70,0,1,5,2
27,STR128,Super Market,Super Market,Kolkata,30.4,40,95.1,113,3.77,1.513,16.90,1,1,5,2
28,STR129,Central Store,Super Market,Kolkata,15.8,80,351.0,264,4.22,3.170,14.50,0,1,5,4
29,STR130,Apparel Zone,Apparel,Kolkata,19.7,60,145.0,175,3.62,2.770,15.50,0,1,5,4
30,STR131,Fashion Bazar,Apparel,Kolkata,15.0,80,301.0,335,3.54,3.570,14.60,0,1,5,4
31,STR132,Digital Bazar,Electronincs,Kolkata,21.4,40,121.0,109,4.11,2.780,18.60,1,1,4,2

In [23]:
s1.index

RangeIndex(start=0, stop=32, step=1)

In [18]:
print(s1.describe)

<bound method NDFrame.describe of    StoreCode         StoreName     StoreType Location  OperatingCost  \
0     STR101  Electronics Zone  Electronincs    Delhi           21.0
1     STR102      Apparel Zone       Apparel    Delhi           21.0
2     STR103       Super Bazar  Super Market    Delhi           22.8
3     STR104      Super Market  Super Market    Delhi           21.4
4     STR105     Central Store  Super Market    Delhi           18.7
5     STR106      Apparel Zone       Apparel    Delhi           18.1
6     STR107     Fashion Bazar       Apparel    Delhi           14.3
7     STR108     Digital Bazar  Electronincs    Delhi           24.4
8     STR109  Electronics Zone  Electronincs  Chennai           22.8
9     STR110      Apparel Zone       Apparel  Chennai           19.2
10    STR111       Super Bazar  Super Market  Chennai           17.8
11    STR112      Super Market  Super Market  Chennai           16.4
12    STR113     Central Store  Super Market  Chennai           17.3
13    STR114      Apparel Zone       Apparel  Chennai           15.2
14    STR115     Fashion Bazar       Apparel  Chennai           10.4
15    STR116     Digital Bazar  Electronincs  Chennai           10.4
16    STR117  Electronics Zone  Electronincs   Mumbai           14.7
17    STR118      Apparel Zone       Apparel   Mumbai           32.4
18    STR119       Super Bazar  Super Market   Mumbai           30.4
19    STR120      Super Market  Super Market   Mumbai           33.9
20    STR121     Central Store  Super Market   Mumbai           21.5
21    STR122      Apparel Zone       Apparel   Mumbai           15.5
22    STR123     Fashion Bazar       Apparel   Mumbai           15.2
23    STR124     Digital Bazar  Electronincs   Mumbai           13.3
24    STR125  Electronics Zone  Electronincs  Kolkata           19.2
25    STR126      Apparel Zone       Apparel  Kolkata           27.3
26    STR127       Super Bazar  Super Market  Kolkata           26.0
27    STR128      Super Market  Super Market  Kolkata           30.4
28    STR129     Central Store  Super Market  Kolkata           15.8
29    STR130      Apparel Zone       Apparel  Kolkata           19.7
30    STR131     Fashion Bazar       Apparel  Kolkata           15.0
31    STR132     Digital Bazar  Electronincs  Kolkata           21.4

    Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0          60       160.0              110            3.90       2.620
1          60       160.0              110            3.90       2.875
2          40       108.0               93            3.85       2.320
3          60       258.0              110            3.08       3.215
4          80       360.0              175            3.15       3.440
5          60       225.0              105            2.76       3.460
6          80       360.0              245            3.21       3.570
7          40       146.7               62            3.69       3.190
8          40       140.8               95            3.92       3.150
9          60       167.6              123            3.92       3.440
10         60       167.6              123            3.92       3.440
11         80       275.8              180             NaN       4.070
12         80       275.8              180             NaN       3.730
13         80       275.8              180             NaN       3.780
14         80       472.0              205            2.93       5.250
15         80       460.0              215            3.00       5.424
16         80       440.0              230            3.23       5.345
17         40        78.7               66            4.08       2.200
18         40        75.7               52            4.93       1.615
19         40        71.1               65            4.22       1.835
20         40       120.1               97            3.70       2.465
21         80       318.0              150            2.76       3.520
22         80       304.0              150            3.15       3.435
23         80       350.0              245            3.73       3.840
24         80       400.0              175            3.08       3.845
25         40        79.0               66            4.08       1.935
26         40       120.3               91            4.43       2.140
27         40        95.1              113            3.77       1.513
28         80       351.0              264            4.22       3.170
29         60       145.0              175            3.62       2.770
30         80       301.0              335            3.54       3.570
31         40       121.0              109            4.11       2.780

    ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment
0           16.46         0               1       4             4
1           17.02         0               1       4             4
2           18.61         1               1       4             1
3           19.44         1               0       3             1
4           17.02         0               0       3             2
5           20.22         1               0       3             1
6           15.84         0               0       3             4
7           20.00         1               0       4             2
8           22.90         1               0       4             2
9           18.30         1               0       4             4
10          18.90         1               0       4             4
11          17.40         0               0       3             3
12          17.60         0               0       3             3
13          18.00         0               0       3             3
14          17.98         0               0       3             4
15          17.82         0               0       3             4
16          17.42         0               0       3             4
17          19.47         1               1       4             1
18          18.52         1               1       4             2
19          19.90         1               1       4             1
20          20.01         1               0       3             1
21          16.87         0               0       3             2
22          17.30         0               0       3             2
23          15.41         0               0       3             4
24          17.05         0               0       3             2
25          18.90         1               1       4             1
26          16.70         0               1       5             2
27          16.90         1               1       5             2
28          14.50         0               1       5             4
29          15.50         0               1       5             4
30          14.60         0               1       5             4
31          18.60         1               1       4             2  >

In [26]:
print(s1.info)

<bound method DataFrame.info of    StoreCode         StoreName     StoreType Location  OperatingCost  \
0     STR101  Electronics Zone  Electronincs    Delhi           21.0
1     STR102      Apparel Zone       Apparel    Delhi           21.0
2     STR103       Super Bazar  Super Market    Delhi           22.8
3     STR104      Super Market  Super Market    Delhi           21.4
4     STR105     Central Store  Super Market    Delhi           18.7
5     STR106      Apparel Zone       Apparel    Delhi           18.1
6     STR107     Fashion Bazar       Apparel    Delhi           14.3
7     STR108     Digital Bazar  Electronincs    Delhi           24.4
8     STR109  Electronics Zone  Electronincs  Chennai           22.8
9     STR110      Apparel Zone       Apparel  Chennai           19.2
10    STR111       Super Bazar  Super Market  Chennai           17.8
11    STR112      Super Market  Super Market  Chennai           16.4
12    STR113     Central Store  Super Market  Chennai           17.3
13    STR114      Apparel Zone       Apparel  Chennai           15.2
14    STR115     Fashion Bazar       Apparel  Chennai           10.4
15    STR116     Digital Bazar  Electronincs  Chennai           10.4
16    STR117  Electronics Zone  Electronincs   Mumbai           14.7
17    STR118      Apparel Zone       Apparel   Mumbai           32.4
18    STR119       Super Bazar  Super Market   Mumbai           30.4
19    STR120      Super Market  Super Market   Mumbai           33.9
20    STR121     Central Store  Super Market   Mumbai           21.5
21    STR122      Apparel Zone       Apparel   Mumbai           15.5
22    STR123     Fashion Bazar       Apparel   Mumbai           15.2
23    STR124     Digital Bazar  Electronincs   Mumbai           13.3
24    STR125  Electronics Zone  Electronincs  Kolkata           19.2
25    STR126      Apparel Zone       Apparel  Kolkata           27.3
26    STR127       Super Bazar  Super Market  Kolkata           26.0
27    STR128      Super Market  Super Market  Kolkata           30.4
28    STR129     Central Store  Super Market  Kolkata           15.8
29    STR130      Apparel Zone       Apparel  Kolkata           19.7
30    STR131     Fashion Bazar       Apparel  Kolkata           15.0
31    STR132     Digital Bazar  Electronincs  Kolkata           21.4

    Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0          60       160.0              110            3.90       2.620
1          60       160.0              110            3.90       2.875
2          40       108.0               93            3.85       2.320
3          60       258.0              110            3.08       3.215
4          80       360.0              175            3.15       3.440
5          60       225.0              105            2.76       3.460
6          80       360.0              245            3.21       3.570
7          40       146.7               62            3.69       3.190
8          40       140.8               95            3.92       3.150
9          60       167.6              123            3.92       3.440
10         60       167.6              123            3.92       3.440
11         80       275.8              180             NaN       4.070
12         80       275.8              180             NaN       3.730
13         80       275.8              180             NaN       3.780
14         80       472.0              205            2.93       5.250
15         80       460.0              215            3.00       5.424
16         80       440.0              230            3.23       5.345
17         40        78.7               66            4.08       2.200
18         40        75.7               52            4.93       1.615
19         40        71.1               65            4.22       1.835
20         40       120.1               97            3.70       2.465
21         80       318.0              150            2.76       3.520
22         80       304.0              150            3.15       3.435
23         80       350.0              245            3.73       3.840
24         80       400.0              175            3.08       3.845
25         40        79.0               66            4.08       1.935
26         40       120.3               91            4.43       2.140
27         40        95.1              113            3.77       1.513
28         80       351.0              264            4.22       3.170
29         60       145.0              175            3.62       2.770
30         80       301.0              335            3.54       3.570
31         40       121.0              109            4.11       2.780

    ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment
0           16.46         0               1       4             4
1           17.02         0               1       4             4
2           18.61         1               1       4             1
3           19.44         1               0       3             1
4           17.02         0               0       3             2
5           20.22         1               0       3             1
6           15.84         0               0       3             4
7           20.00         1               0       4             2
8           22.90         1               0       4             2
9           18.30         1               0       4             4
10          18.90         1               0       4             4
11          17.40         0               0       3             3
12          17.60         0               0       3             3
13          18.00         0               0       3             3
14          17.98         0               0       3             4
15          17.82         0               0       3             4
16          17.42         0               0       3             4
17          19.47         1               1       4             1
18          18.52         1               1       4             2
19          19.90         1               1       4             1
20          20.01         1               0       3             1
21          16.87         0               0       3             2
22          17.30         0               0       3             2
23          15.41         0               0       3             4
24          17.05         0               0       3             2
25          18.90         1               1       4             1
26          16.70         0               1       5             2
27          16.90         1               1       5             2
28          14.50         0               1       5             4
29          15.50         0               1       5             4
30          14.60         0               1       5             4
31          18.60         1               1       4             2  >

In [8]:
import pandas as pd
data =[33,34,40,41,36]
year = [2002,2003,2010,2002,2008]
s =pd.Series(data,index=year,name='data')
print(s)
print(s[2002])

2002    33
2003    34
2010    40
2002    41
2008    36
Name: data, dtype: int64
2002    33
2002    41
Name: data, dtype: int64

In [10]:
s.index

Index([2002, 2003, 2010, 2002, 2008], dtype='int64')

In [11]:
s.index.is_unique

False

In [12]:
s

2002    33
2003    34
2010    40
2002    41
2008    36
Name: data, dtype: int64

In [15]:
# loc -> location  and iloc -> index Location
s.loc[2002]=45
s

2002    45
2003    34
2010    40
2002    45
2008    36
Name: data, dtype: int64

## .iloc and .loc

In [17]:
s.loc[2002]
s

2002    45
2003    34
2010    40
2002    45
2008    36
Name: data, dtype: int64

In [20]:
s.iloc[-1]
s.iloc[-2]
s.iloc[-3]
s.iloc[-4]

np.int64(34)

In [21]:
s.iloc[9]

IndexError: single positional indexer is out-of-bounds

In [22]:
print(s)
s.iloc[[2,4]]

2002    45
2003    34
2010    40
2002    45
2008    36
Name: data, dtype: int64

2010    40
2008    36
Name: data, dtype: int64

In [26]:
s.iloc[2:5]

2010    40
2002    45
2008    36
Name: data, dtype: int64

In [24]:
print(s.loc[2001])
print(s[2001])

KeyError: 2001

In [25]:
s.loc[[2002],2003]

IndexingError: Too many indexers

## .at and .iat

### the .at and .iat index accessors are analogous to .loc and .iloc . The difference being that they will return a numpy .ndarray when pulling out a duplicate value, whereas .loc and .iloc return a series

In [35]:
s.iat[1]
print(s.iat[1],type(s.at[2001]))

KeyError: 2001

In [29]:
type(s.at[2002])

pandas.Series

In [36]:
s.iloc[-3:]

2010    40
2002    45
2008    36
Name: data, dtype: int64

In [ ]:
s.iloc[::-2]  #backword me print karega

2008    36
2010    40
2002    45
Name: data, dtype: int64

In [38]:
s.iloc[::2]

2002    45
2010    40
2008    36
Name: data, dtype: int64

In [39]:
s.iloc[::-1]

2008    36
2002    45
2010    40
2003    34
2002    45
Name: data, dtype: int64

copy paste karna hai

## Boolean Array indexing

In [40]:
print(s)
s[s>35]

2002    45
2003    34
2010    40
2002    45
2008    36
Name: data, dtype: int64

2002    45
2010    40
2002    45
2008    36
Name: data, dtype: int64

## Multiple Boolean Operation

In [43]:
s[(s>35)&(s<41)]

2010    40
2008    36
Name: data, dtype: int64

## Series Method
## .items Method

In [46]:
import pandas as pd
import numpy as np
s = pd.Series(np.arange(1,10,2))
s

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [47]:
for value in s:
    print(value)

1
3
5
7
9

In [48]:
for item in s.items(): #use items()
    print(item)

(0, 1)
(1, 3)
(2, 5)
(3, 7)
(4, 9)

In [ ]:
# Iteration over the index and value pairs
for idx,value in s.items():
    print(idx,value)

0 1
1 3
2 5
3 7
4 9

## .key Method

In [53]:
# print(s.keys)
print(s)
for idx in s.keys():
    print(idx)

0    1
1    3
2    5
3    7
4    9
dtype: int64
0
1
2
3
4

In [56]:
s1 = pd.Series([22,34,45,56],index=['Abdul','Malik','Khan','Madani'],name='age')
for idx in s1.keys():
    print(idx,"=>",s1[idx])

Abdul => 22
Malik => 34
Khan => 45
Madani => 56

In [3]:
import pandas as pd
s = pd.Series([10,20,30,40,50],index=['r1','r2','r3','r4','r5'])
s

r1    10
r2    20
r3    30
r4    40
r5    50
dtype: int64

In [4]:
s+s['r1']

r1    20
r2    30
r3    40
r4    50
r5    60
dtype: int64

In [5]:
# Addition of two series
s1 = pd.Series([12,13,14,15])
s2 = pd.Series([1,2,3,4,5,6])
s1+s2

0    13.0
1    15.0
2    17.0
3    19.0
4     NaN
5     NaN
dtype: float64

In [6]:
#subtraction of two series
s1-s2

0    11.0
1    11.0
2    11.0
3    11.0
4     NaN
5     NaN
dtype: float64

In [ ]:
#Multiplication of two series
s1*s2

0    12.0
1    26.0
2    42.0
3    60.0
4     NaN
5     NaN
dtype: float64

In [ ]:
# Divide of two series
s1/s2

0    12.000000
1     6.500000
2     4.666667
3     3.750000
4          NaN
5          NaN
dtype: float64

In [11]:
s1//s2

0    12.0
1     6.0
2     4.0
3     3.0
4     NaN
5     NaN
dtype: float64

In [10]:
s1==s1

0    True
1    True
2    True
3    True
dtype: bool

### Reset Index

* The reset_index() function is used to generate a new DataFrame or Series with the index reset.
* This is useful when the index needs to be treated as a column,or when the index is meaningless

Series.reset_index(self,level=None,drop=false,name=None,inplace=False)

In [12]:
# Create a series
s = pd.Series([2,3,4,5],name = 'f1',index=pd.Index(['p','q','r','s'],name='idx'))
s

idx
p    2
q    3
r    4
s    5
Name: f1, dtype: int64

In [20]:
# Generate a dataframe with default index
x = s.reset_index()
print(type(x))

print(type(s.reset_index()))

<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>

In [21]:
s.reset_index(name="values")

  idx  values
0   p       2
1   q       3
2   r       4
3   s       5

In [22]:
s.reset_index(drop=True)

0    2
1    3
2    4
3    5
Name: f1, dtype: int64

In [24]:
s

0    2
1    3
2    4
3    5
Name: f1, dtype: int64

In [26]:
s.reset_index(inplace=True,drop=True)
s

0    2
1    3
2    4
3    5
Name: f1, dtype: int64

### Counts

the .count method returns the number of non null items

In [28]:
s = pd.Series([100,23.4,100,None,44],name='value')
s

0    100.0
1     23.4
2    100.0
3      NaN
4     44.0
Name: value, dtype: float64

In [29]:
s.count()

np.int64(4)

### .value_counts

In [30]:
s.value_counts()

value
100.0    2
23.4     1
44.0     1
Name: count, dtype: int64