# EDA WALA PART START

## EDA (Exploratory Data Analysis)

1. Load the Data
2. Look at it    --- first row,shape,columns,datatypes
3. Summarize     --- statistics,unique
4. Find problems --- missing vlaues,duplicates,wrong types,outliers
5. Clean         --- fix or removes the problems
6. Explore relationships ---  group, compare,correlate

## Setup - run this time

In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.set_option('display.max_columns', None)  # show all columns
print('Libraries loaded.pandas',pd.__version__)

Libraries loaded.pandas 3.0.5

## Level - 1

In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Abdul\OneDrive\Documents\students.csv")
df.head()

   RollNo          Name  Gender   Age  Attendance  Marks Department
0     101   Ishan Singh  Female  20.0        65.3   66.0         ME
1     102   Aditya Khan       F  17.0        62.9   53.0        ECE
2     103   Ishan Mehta  female  17.0        99.2   75.0         ME
3     104  Kabeer Reddy       M  18.0        78.2   82.0         CE
4     105   Vivaan Khan    Male  20.0        66.7   89.0        CSE

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   RollNo      61 non-null     int64
 1   Name        61 non-null     str
 2   Gender      59 non-null     str
 3   Age         57 non-null     float64
 4   Attendance  56 non-null     float64
 5   Marks       58 non-null     float64
 6   Department  61 non-null     str
dtypes: float64(3), int64(1), str(3)
memory usage: 3.5 KB

In [6]:
print('columns names:',list(df.columns))
print()
print('Data types:')
print(df.dtypes)

columns names: ['RollNo', 'Name', 'Gender', 'Age', 'Attendance', 'Marks', 'Department']

Data types:
RollNo          int64
Name              str
Gender            str
Age           float64
Attendance    float64
Marks         float64
Department        str
dtype: object

In [7]:
df.shape[1]

7

## Summary statistic -- describe()

In [8]:
df.describe()

           RollNo        Age  Attendance       Marks
count   61.000000  57.000000   56.000000   58.000000
mean   130.180328  18.649123   80.130357   71.206897
std     17.497150   1.356087   12.642740   30.419730
min    101.000000  17.000000   55.800000   31.000000
25%    115.000000  17.000000   68.475000   53.250000
50%    130.000000  19.000000   78.800000   69.500000
75%    145.000000  20.000000   91.000000   87.000000
max    160.000000  21.000000   99.800000  250.000000

In [9]:
df['RollNo'].describe()

count     61.000000
mean     130.180328
std       17.497150
min      101.000000
25%      115.000000
50%      130.000000
75%      145.000000
max      160.000000
Name: RollNo, dtype: float64

In [10]:
df['Age'].describe()

count    57.000000
mean     18.649123
std       1.356087
min      17.000000
25%      17.000000
50%      19.000000
75%      20.000000
max      21.000000
Name: Age, dtype: float64

## value_counts()  and unique()  --- single column

In [11]:
df['Gender'].value_counts()

Gender
F         13
female    11
Male      11
male      11
M          8
Female     5
Name: count, dtype: int64

In [12]:
df['Department'].value_counts()

Department
CE     19
ECE    15
CSE    14
ME     13
Name: count, dtype: int64

In [13]:
print(df['Gender'].unique())
print(df['Gender'].nunique())

<StringArray>
['Female', 'F', 'female', 'M', 'Male', 'male', nan]
Length: 7, dtype: str
6

In [14]:
df['Department'].value_counts()

Department
CE     19
ECE    15
CSE    14
ME     13
Name: count, dtype: int64

## FINDING MISSING VALUES --  isnull().sum()

In [16]:
df.isnull().sum().sum()

np.int64(14)

In [17]:
print('Duplicate rows:',df.duplicated().sum())
df[df.duplicated()]

Duplicate rows: 1

    RollNo         Name  Gender   Age  Attendance  Marks Department
60     111  Aarav Mehta  female  17.0        67.5   54.0         CE

## Cleaning the Data

In [ ]:
# Remove duplicates rows
df = df.drop_duplicates()
print('Shape after removing duplicates:',df.shape)

Shape after removing duplicates: (60, 7)

In [20]:
df.loc[df['Marks']>100,'Marks'] = np.nan
print('Max marks now:',df['Marks'].max())

Max marks now: 99.0

In [26]:
## Fill missing values with mean of the column
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].median())
print('Missing values now:')
print(df[['Marks','Age','Attendance']].isnull().sum())
print(df[['Marks','Age','Attendance']].isnull().sum().sum())

Missing values now:
Marks         0
Age           0
Attendance    0
dtype: int64
0

In [27]:
## Standardize the Gender labels
gender_map = {'M':'Male','F':'Female'}
df['Gender'] = df['Gender'].replace(gender_map)
df['Gender'].value_counts()

Gender
Male      19
Female    18
male      11
female    10
Name: count, dtype: int64