### Dictionary

In [2]:
# Dictionary
data = {'student':['Jatin','Mitali','Rohan','Zubair'],
        'year':[1,2,3,1],
        'marks': [9.8,6.7,8,9.9]}

In [5]:
import pandas as pd
df = pd.DataFrame(data)
df

  student  year  marks
0   Jatin     1    9.8
1  Mitali     2    6.7
2   Rohan     3    8.0
3  Zubair     1    9.9

In [8]:
import pandas as pd
df = pd.DataFrame(data)
print(df)

print(df.head(2))
print(df.tail(2))

  student  year  marks
0   Jatin     1    9.8
1  Mitali     2    6.7
2   Rohan     3    8.0
3  Zubair     1    9.9
  student  year  marks
0   Jatin     1    9.8
1  Mitali     2    6.7
  student  year  marks
2   Rohan     3    8.0
3  Zubair     1    9.9

### Note - the type of column is a pandas series instance

In [15]:
# Type of column
print(df)
type(df['student'])
type(df['marks'])
type(df['year'])

  student  year  marks
0   Jatin     1    9.8
1  Mitali     2    6.7
2   Rohan     3    8.0
3  Zubair     1    9.9

pandas.Series

In [16]:
df['student'].str.upper()

0     JATIN
1    MITALI
2     ROHAN
3    ZUBAIR
Name: student, dtype: str

## Construction of DataFrame

### Data Frames can be created from many types of input:
* columns (dicts of list)
* rows (list of dicts)
* CSV file(pd.read_csv)
* from NumPy ndarray
* and more,SQL,HDF5,etc

In [29]:
x = np.arange(1,21).reshape(5,4)
print("Array is :",x)
y = pd.DataFrame(x,columns=['A','B','C','D'])
print("DataFrame is :",y)

Array is : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
DataFrame is :     A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20

### List of dictionary

In [33]:
# row wise appendic data
l = [{'student':'jatin','year':1,'marks':9.9},
     {'student':'Abdul','Year':2,'marks':6.7}]
df = pd.DataFrame(l)
df

  student  year  marks  Year
0   jatin   1.0    9.9   NaN
1   Abdul   NaN    6.7   2.0

In [34]:
l = [{'student':'jatin','year':1,'marks':9.9},
     {'student':'Abdul','Year':2,}]
df = pd.DataFrame(l)
df

  student  year  marks  Year
0   jatin   1.0    9.9   NaN
1   Abdul   NaN    NaN   2.0

### Data Frame Axis

In [30]:
df.axes

[RangeIndex(start=0, stop=2, step=1),
 Index(['student', 'year', 'marks', 'Year'], dtype='str')]

In [31]:
df.axes[0]

RangeIndex(start=0, stop=2, step=1)

In [32]:
df.axes[1]

Index(['student', 'year', 'marks', 'Year'], dtype='str')

## Data Selection in DataFrame

In [40]:
df = pd.read_csv(r"C:\Users\Abdul\OneDrive\Documents\stores.csv")
print(df)

   StoreCode         StoreName     StoreType Location  OperatingCost  \
0     STR101  Electronics Zone  Electronincs    Delhi           21.0
1     STR102      Apparel Zone       Apparel    Delhi           21.0
2     STR103       Super Bazar  Super Market    Delhi           22.8
3     STR104      Super Market  Super Market    Delhi           21.4
4     STR105     Central Store  Super Market    Delhi           18.7
5     STR106      Apparel Zone       Apparel    Delhi           18.1
6     STR107     Fashion Bazar       Apparel    Delhi           14.3
7     STR108     Digital Bazar  Electronincs    Delhi           24.4
8     STR109  Electronics Zone  Electronincs  Chennai           22.8
9     STR110      Apparel Zone       Apparel  Chennai           19.2
10    STR111       Super Bazar  Super Market  Chennai           17.8
11    STR112      Super Market  Super Market  Chennai           16.4
12    STR113     Central Store  Super Market  Chennai           17.3
13    STR114      Apparel Zone       Apparel  Chennai           15.2
14    STR115     Fashion Bazar       Apparel  Chennai           10.4
15    STR116     Digital Bazar  Electronincs  Chennai           10.4
16    STR117  Electronics Zone  Electronincs   Mumbai           14.7
17    STR118      Apparel Zone       Apparel   Mumbai           32.4
18    STR119       Super Bazar  Super Market   Mumbai           30.4
19    STR120      Super Market  Super Market   Mumbai           33.9
20    STR121     Central Store  Super Market   Mumbai           21.5
21    STR122      Apparel Zone       Apparel   Mumbai           15.5
22    STR123     Fashion Bazar       Apparel   Mumbai           15.2
23    STR124     Digital Bazar  Electronincs   Mumbai           13.3
24    STR125  Electronics Zone  Electronincs  Kolkata           19.2
25    STR126      Apparel Zone       Apparel  Kolkata           27.3
26    STR127       Super Bazar  Super Market  Kolkata           26.0
27    STR128      Super Market  Super Market  Kolkata           30.4
28    STR129     Central Store  Super Market  Kolkata           15.8
29    STR130      Apparel Zone       Apparel  Kolkata           19.7
30    STR131     Fashion Bazar       Apparel  Kolkata           15.0
31    STR132     Digital Bazar  Electronincs  Kolkata           21.4

    Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0          60       160.0              110            3.90       2.620
1          60       160.0              110            3.90       2.875
2          40       108.0               93            3.85       2.320
3          60       258.0              110            3.08       3.215
4          80       360.0              175            3.15       3.440
5          60       225.0              105            2.76       3.460
6          80       360.0              245            3.21       3.570
7          40       146.7               62            3.69       3.190
8          40       140.8               95            3.92       3.150
9          60       167.6              123            3.92       3.440
10         60       167.6              123            3.92       3.440
11         80       275.8              180             NaN       4.070
12         80       275.8              180             NaN       3.730
13         80       275.8              180             NaN       3.780
14         80       472.0              205            2.93       5.250
15         80       460.0              215            3.00       5.424
16         80       440.0              230            3.23       5.345
17         40        78.7               66            4.08       2.200
18         40        75.7               52            4.93       1.615
19         40        71.1               65            4.22       1.835
20         40       120.1               97            3.70       2.465
21         80       318.0              150            2.76       3.520
22         80       304.0              150            3.15       3.435
23         80       350.0              245            3.73       3.840
24         80       400.0              175            3.08       3.845
25         40        79.0               66            4.08       1.935
26         40       120.3               91            4.43       2.140
27         40        95.1              113            3.77       1.513
28         80       351.0              264            4.22       3.170
29         60       145.0              175            3.62       2.770
30         80       301.0              335            3.54       3.570
31         40       121.0              109            4.11       2.780

    ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment
0           16.46         0               1       4             4
1           17.02         0               1       4             4
2           18.61         1               1       4             1
3           19.44         1               0       3             1
4           17.02         0               0       3             2
5           20.22         1               0       3             1
6           15.84         0               0       3             4
7           20.00         1               0       4             2
8           22.90         1               0       4             2
9           18.30         1               0       4             4
10          18.90         1               0       4             4
11          17.40         0               0       3             3
12          17.60         0               0       3             3
13          18.00         0               0       3             3
14          17.98         0               0       3             4
15          17.82         0               0       3             4
16          17.42         0               0       3             4
17          19.47         1               1       4             1
18          18.52         1               1       4             2
19          19.90         1               1       4             1
20          20.01         1               0       3             1
21          16.87         0               0       3             2
22          17.30         0               0       3             2
23          15.41         0               0       3             4
24          17.05         0               0       3             2
25          18.90         1               1       4             1
26          16.70         0               1       5             2
27          16.90         1               1       5             2
28          14.50         0               1       5             4
29          15.50         0               1       5             4
30          14.60         0               1       5             4
31          18.60         1               1       4             2

In [50]:
place = df[['Location','StoreType']]
place

   Location     StoreType
0     Delhi  Electronincs
1     Delhi       Apparel
2     Delhi  Super Market
3     Delhi  Super Market
4     Delhi  Super Market
5     Delhi       Apparel
6     Delhi       Apparel
7     Delhi  Electronincs
8   Chennai  Electronincs
9   Chennai       Apparel
10  Chennai  Super Market
11  Chennai  Super Market
12  Chennai  Super Market
13  Chennai       Apparel
14  Chennai       Apparel
15  Chennai  Electronincs
16   Mumbai  Electronincs
17   Mumbai       Apparel
18   Mumbai  Super Market
19   Mumbai  Super Market
20   Mumbai  Super Market
21   Mumbai       Apparel
22   Mumbai       Apparel
23   Mumbai  Electronincs
24  Kolkata  Electronincs
25  Kolkata       Apparel
26  Kolkata  Super Market
27  Kolkata  Super Market
28  Kolkata  Super Market
29  Kolkata       Apparel
30  Kolkata       Apparel
31  Kolkata  Electronincs

In [ ]:
df.StoreType   # ya df['store']

0     Electronincs
1          Apparel
2     Super Market
3     Super Market
4     Super Market
5          Apparel
6          Apparel
7     Electronincs
8     Electronincs
9          Apparel
10    Super Market
11    Super Market
12    Super Market
13         Apparel
14         Apparel
15    Electronincs
16    Electronincs
17         Apparel
18    Super Market
19    Super Market
20    Super Market
21         Apparel
22         Apparel
23    Electronincs
24    Electronincs
25         Apparel
26    Super Market
27    Super Market
28    Super Market
29         Apparel
30         Apparel
31    Electronincs
Name: StoreType, dtype: str

In [54]:
df.rank

<bound method NDFrame.rank of    StoreCode         StoreName     StoreType Location  OperatingCost  \
0     STR101  Electronics Zone  Electronincs    Delhi           21.0
1     STR102      Apparel Zone       Apparel    Delhi           21.0
2     STR103       Super Bazar  Super Market    Delhi           22.8
3     STR104      Super Market  Super Market    Delhi           21.4
4     STR105     Central Store  Super Market    Delhi           18.7
5     STR106      Apparel Zone       Apparel    Delhi           18.1
6     STR107     Fashion Bazar       Apparel    Delhi           14.3
7     STR108     Digital Bazar  Electronincs    Delhi           24.4
8     STR109  Electronics Zone  Electronincs  Chennai           22.8
9     STR110      Apparel Zone       Apparel  Chennai           19.2
10    STR111       Super Bazar  Super Market  Chennai           17.8
11    STR112      Super Market  Super Market  Chennai           16.4
12    STR113     Central Store  Super Market  Chennai           17.3
13    STR114      Apparel Zone       Apparel  Chennai           15.2
14    STR115     Fashion Bazar       Apparel  Chennai           10.4
15    STR116     Digital Bazar  Electronincs  Chennai           10.4
16    STR117  Electronics Zone  Electronincs   Mumbai           14.7
17    STR118      Apparel Zone       Apparel   Mumbai           32.4
18    STR119       Super Bazar  Super Market   Mumbai           30.4
19    STR120      Super Market  Super Market   Mumbai           33.9
20    STR121     Central Store  Super Market   Mumbai           21.5
21    STR122      Apparel Zone       Apparel   Mumbai           15.5
22    STR123     Fashion Bazar       Apparel   Mumbai           15.2
23    STR124     Digital Bazar  Electronincs   Mumbai           13.3
24    STR125  Electronics Zone  Electronincs  Kolkata           19.2
25    STR126      Apparel Zone       Apparel  Kolkata           27.3
26    STR127       Super Bazar  Super Market  Kolkata           26.0
27    STR128      Super Market  Super Market  Kolkata           30.4
28    STR129     Central Store  Super Market  Kolkata           15.8
29    STR130      Apparel Zone       Apparel  Kolkata           19.7
30    STR131     Fashion Bazar       Apparel  Kolkata           15.0
31    STR132     Digital Bazar  Electronincs  Kolkata           21.4

    Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0          60       160.0              110            3.90       2.620
1          60       160.0              110            3.90       2.875
2          40       108.0               93            3.85       2.320
3          60       258.0              110            3.08       3.215
4          80       360.0              175            3.15       3.440
5          60       225.0              105            2.76       3.460
6          80       360.0              245            3.21       3.570
7          40       146.7               62            3.69       3.190
8          40       140.8               95            3.92       3.150
9          60       167.6              123            3.92       3.440
10         60       167.6              123            3.92       3.440
11         80       275.8              180             NaN       4.070
12         80       275.8              180             NaN       3.730
13         80       275.8              180             NaN       3.780
14         80       472.0              205            2.93       5.250
15         80       460.0              215            3.00       5.424
16         80       440.0              230            3.23       5.345
17         40        78.7               66            4.08       2.200
18         40        75.7               52            4.93       1.615
19         40        71.1               65            4.22       1.835
20         40       120.1               97            3.70       2.465
21         80       318.0              150            2.76       3.520
22         80       304.0              150            3.15       3.435
23         80       350.0              245            3.73       3.840
24         80       400.0              175            3.08       3.845
25         40        79.0               66            4.08       1.935
26         40       120.3               91            4.43       2.140
27         40        95.1              113            3.77       1.513
28         80       351.0              264            4.22       3.170
29         60       145.0              175            3.62       2.770
30         80       301.0              335            3.54       3.570
31         40       121.0              109            4.11       2.780

    ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment
0           16.46         0               1       4             4
1           17.02         0               1       4             4
2           18.61         1               1       4             1
3           19.44         1               0       3             1
4           17.02         0               0       3             2
5           20.22         1               0       3             1
6           15.84         0               0       3             4
7           20.00         1               0       4             2
8           22.90         1               0       4             2
9           18.30         1               0       4             4
10          18.90         1               0       4             4
11          17.40         0               0       3             3
12          17.60         0               0       3             3
13          18.00         0               0       3             3
14          17.98         0               0       3             4
15          17.82         0               0       3             4
16          17.42         0               0       3             4
17          19.47         1               1       4             1
18          18.52         1               1       4             2
19          19.90         1               1       4             1
20          20.01         1               0       3             1
21          16.87         0               0       3             2
22          17.30         0               0       3             2
23          15.41         0               0       3             4
24          17.05         0               0       3             2
25          18.90         1               1       4             1
26          16.70         0               1       5             2
27          16.90         1               1       5             2
28          14.50         0               1       5             4
29          15.50         0               1       5             4
30          14.60         0               1       5             4
31          18.60         1               1       4             2  >

In [57]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
StoreCode,STR101,STR102,STR103,STR104,STR105,STR106,STR107,STR108,STR109,STR110,...,STR123,STR124,STR125,STR126,STR127,STR128,STR129,STR130,STR131,STR132
StoreName,Electronics Zone,Apparel Zone,Super Bazar,Super Market,Central Store,Apparel Zone,Fashion Bazar,Digital Bazar,Electronics Zone,Apparel Zone,...,Fashion Bazar,Digital Bazar,Electronics Zone,Apparel Zone,Super Bazar,Super Market,Central Store,Apparel Zone,Fashion Bazar,Digital Bazar
StoreType,Electronincs,Apparel,Super Market,Super Market,Super Market,Apparel,Apparel,Electronincs,Electronincs,Apparel,...,Apparel,Electronincs,Electronincs,Apparel,Super Market,Super Market,Super Market,Apparel,Apparel,Electronincs
Location,Delhi,Delhi,Delhi,Delhi,Delhi,Delhi,Delhi,Delhi,Chennai,Chennai,...,Mumbai,Mumbai,Kolkata,Kolkata,Kolkata,Kolkata,Kolkata,Kolkata,Kolkata,Kolkata
OperatingCost,21.0,21.0,22.8,21.4,18.7,18.1,14.3,24.4,22.8,19.2,...,15.2,13.3,19.2,27.3,26.0,30.4,15.8,19.7,15.0,21.4
Staff_Cnt,60,60,40,60,80,60,80,40,40,60,...,80,80,80,40,40,40,80,60,80,40
TotalSales,160.0,160.0,108.0,258.0,360.0,225.0,360.0,146.7,140.8,167.6,...,304.0,350.0,400.0,79.0,120.3,95.1,351.0,145.0,301.0,121.0
Total_Customers,110,110,93,110,175,105,245,62,95,123,...,150,245,175,66,91,113,264,175,335,109
AcqCostPercust,3.9,3.9,3.85,3.08,3.15,2.76,3.21,3.69,3.92,3.92,...,3.15,3.73,3.08,4.08,4.43,3.77,4.22,3.62,3.54,4.11
BasketSize,2.62,2.875,2.32,3.215,3.44,3.46,3.57,3.19,3.15,3.44,...,3.435,3.84,3.845,1.935,2.14,1.513,3.17,2.77,3.57,2.78
ProfitPercust,16.46,17.02,18.61,19.44,17.02,20.22,15.84,20.0,22.9,18.3,...,17.3,15.41,17.05,18.9,16.7,16.9,14.5,15.5,14.6,18.6
OwnStore,0,0,1,1,0,1,0,1,1,1,...,0,0,0,1,0,1,0,0,0,1
OnlinePresence,1,1,1,0,0,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,1
Tenure,4,4,4,3,3,3,3,4,4,4,...,3,3,3,4,5,5,5,5,5,4
StoreSegment,4,4,1,1,2,1,4,2,2,4,...,2,4,2,1,2,2,4,4,4,2

In [2]:
import pandas as pd